[package]
name = "statical"
version = "0.1.0"
authors = ["Elio Grieco <grieco@egx.com>"]
edition = "2021"
description = "A calendar aggregator and generator to make maintaining calendars on static websites easier."
readme = "README.md"
# repository = "https://github.com/egrieco/statical"
license = "MIT" # https://spdx.org/licenses/
keywords = []   # free text
categories = [] # https://crates.io/category_slugs
# https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "main"
harness = false

[dependencies]
chrono = "0.4.19"
chrono-tz = "0.6.1"
clap = { version = "3.1.17", features = ["derive"] }
color-eyre = "0.6.1"
dedup_iter = "0.1.1"
ical = "0.7.0"
regex = "1.5.5"
rrule = "0.7.3"
serde = { version = "1.0.137", features = ["derive", "rc"] }
serde_json = "1.0.81"
tera = "1.15.0"
time = { version = "0.3.9", features = ["parsing", "serde-well-known"] }
time-tz = { version = "1.0.1", features = ["db"] }
ureq = "2.4.0"
# serde = { version = "1", features = ["derive"] }
# config = { version = "0", features = ["hjson"] }  # also supports ini, yaml
# termcolor = "1"
# dialoguer = "0"
# fuzzy-matcher = "0"  # fuzzy string-matching
# tabwriter = "1"  # tab-aligned printing
# regex = "1"
# cmd_lib = "0"
# float-cmp = "0"
# maplit = "1"
# auto_enums = "0"  # return multiple types from the same fn
# derive_builder = "0"
# wyz = "0"  # myrrlyn's utils
# derivative = "2"
# derive_more = "0"
# fasteval = "0"  # calculator language

[dev-dependencies]
pretty_assertions = "1.2.1"
indoc = "1.0.6"
criterion = "0.3.5"
